;;; private.el --- Private configuration -*- lexical-binding: t; -*-
;;; Commentary:
;; This file contains private configuration (emails, accounts, etc.)
;; Email configuration is now generated by generate.py from accounts.yaml

;;; Code:

;; Mastodon
(setq mastodon-instance-url "https://fosstodon.org"
      mastodon-active-user "sbfnk")

;;; private.el ends here
